---
title: "HW01 - Getting started with Rmd files"
subtitle: "Stat 133, Fall 2016, Prof. Sanchez"
author: "Your Name"
output: html_document
---

The purpose of this assignment is to work with an `Rmd` file and practice 
writing content using the markdown language.

Log in to bCourses and read "Chapter 1: What is Data Science" from the book 
_Doing Data Science_ (by Rachel Schutt and Cathy O'Neil, 2014).

Write an essay about the assigned reading, using an `Rmd` file.

Focus on the following questions:

- What do you understand by "Data Science"?
- What do you understand by "Big Data"?
- How would you define the concept of "Datafication"?
- Refer to Drew Conway's [Venn diagram of data science](http://drewconway.com/zia/2013/3/26/the-data-science-venn-diagram); 
In which region of the diagram is more likely to locate yourself?


## Requirements

Write an essay of approximately 5000 characters long. 
Name your `Rmd` file using the following format: `stat133-hw01-first-last.Rmd` where "first" and "last" are your first and last names. For instance:
`stat133-hw01-gaston-sanchez.Rmd`.

Your essay must have three main sections: 1) Introduction, 2) Discussion, and
3) Conclusions. You can include other sections and subsections if you want.

Make sure to include the following elements (using markdown syntax):

- Use various types of headings
- Use text in italics
- Use text in bold
- Hyperlinks
- Link of "Data Science" venn diagram image: [http://static1.squarespace.com/static/5150aec6e4b0e340ec52710a/t/51525c33e4b0b3e0d10f77ab/1364352052403/Data_Science_VD.png](http://static1.squarespace.com/static/5150aec6e4b0e340ec52710a/t/51525c33e4b0b3e0d10f77ab/1364352052403/Data_Science_VD.png)
- Cross-reference links
- A table
- Unordered list
- Ordered list
- Blockquote
- Code block
- Inline code
- Breaklines

-----
