---
title: "Lab 5, Stat 133, Fall 2016"
author: "Gaston Sanchez"
output: html_document
---

> ### Learning Objectives
>
> - Using RStudio Projects
> - Toy Data Analysis Project
> - Structure a Project


## Bay Area Bike Accidents Project

The purpose of this lab is to help you prepare your first deliverable project 
of the course.


##  Project Structure

You will use this file structure for this project :
```
project/
	data/
	code/
	images/
	slides/
	README.md
```

The directory `project/` will contain four subdirectories:

- `data/` contains the data sets: raw data, clean data, 
as well as other derived data sets.
- `code/` contains all (or most) of your code in R
- `images/` contains the generated graphics and plots
- `slides/` contains the slide file(s)

There is also a `README.md` file with text about the description of the project,
how it's organized, and the important details.


### More Details

The subdirectories will have files like this:
```
project/
	data/
		bike-accidents.csv
		tables/
			accs-per-year.csv
			accs-per-month.csv
			accs-per-hour.csv
			accs-per-county.csv
	code/
		download-data.R
		univariate-tables.R
		bivariate-tables.R
		univariate-charts.R
		bivariate-charts.R
	images/
		barchart-per-year.png
		barchart-per-month.png
		linechart-per-hour.png
		barchart-per-county.png
	slides/
		slides.Rmd
		slides.html
	README.md
```


-----

### References

- [Using RStudio Projects](https://support.rstudio.com/hc/en-us/articles/200526207-Using-Projects)

-----
